/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrizesRouteImport } from './routes/prizes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomJoinRouteImport } from './routes/room/join'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesRoute = PrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomJoinRoute = RoomJoinRouteImport.update({
  id: '/room/join',
  path: '/room/join',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prizes': typeof PrizesRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/shop': typeof ShopRoute
  '/tutorial': typeof TutorialRoute
  '/wallet': typeof WalletRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/join': typeof RoomJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prizes': typeof PrizesRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/shop': typeof ShopRoute
  '/tutorial': typeof TutorialRoute
  '/wallet': typeof WalletRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/join': typeof RoomJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prizes': typeof PrizesRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/shop': typeof ShopRoute
  '/tutorial': typeof TutorialRoute
  '/wallet': typeof WalletRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/join': typeof RoomJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prizes'
    | '/profile'
    | '/queue'
    | '/shop'
    | '/tutorial'
    | '/wallet'
    | '/room/$roomId'
    | '/room/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prizes'
    | '/profile'
    | '/queue'
    | '/shop'
    | '/tutorial'
    | '/wallet'
    | '/room/$roomId'
    | '/room/join'
  id:
    | '__root__'
    | '/'
    | '/prizes'
    | '/profile'
    | '/queue'
    | '/shop'
    | '/tutorial'
    | '/wallet'
    | '/room/$roomId'
    | '/room/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrizesRoute: typeof PrizesRoute
  ProfileRoute: typeof ProfileRoute
  QueueRoute: typeof QueueRoute
  ShopRoute: typeof ShopRoute
  TutorialRoute: typeof TutorialRoute
  WalletRoute: typeof WalletRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  RoomJoinRoute: typeof RoomJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes': {
      id: '/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof PrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/join': {
      id: '/room/join'
      path: '/room/join'
      fullPath: '/room/join'
      preLoaderRoute: typeof RoomJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrizesRoute: PrizesRoute,
  ProfileRoute: ProfileRoute,
  QueueRoute: QueueRoute,
  ShopRoute: ShopRoute,
  TutorialRoute: TutorialRoute,
  WalletRoute: WalletRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  RoomJoinRoute: RoomJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
